language:       node_js
node_js:
  - "8"
  - "6"
dist:           trusty
before_install:
  - pip install --user codecov    #Install codecov
after_success:
  - npm run report-coverage       #Run codecov
